version: "3.7"
networks:
  mynetwork:
    driver: overlay

volumes:
  mysql_db:
  prometheus_volume: {}

services:
  db:
    networks:
      mynetwork:
    image: nflorina/idp-database
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_db:/var/lib/mysql

  app:
    networks:
      mynetwork:
    image: nflorina/idp-backend-server
    container_name: app_run
    links:
      - db
    ports:
      - "5000:5000"

  admin:
    networks:
      mynetwork:
    image: nflorina/idp-admin
    stdin_open: true
    tty: true
    links:
      - db
    ports:
      - "5100:5000"

  client:
    networks:
      mynetwork:
    image: nflorina/idp-client
    stdin_open: true
    tty: true
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - mynetwork

