version: "3.7"
networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_db:

services:
  db:
    networks:
      mynetwork:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .:/docker-entrypoint-initdb.d/:rw
      - mysql_db:/var/lib/mysql

  app:
    networks:
      mynetwork:
    image: nflorina/idp-backend-server
    links:
      - db
    ports:
      - "5000:5000"

  admin:
    networks:
      mynetwork:
    image: nflorina/idp-admin
    links:
      - db
    ports:
      - "5100:5000"

  client:
    networks:
      mynetwork:
    image: nflorina/idp-client
    ports:
      - "8080:80"

